CREATE TABLE Pais
(
	id INT NOT NULL AUTO_INCREMENT,
	numero INT NOT NULL,
	codigoLongo CHAR(3) NOT NULL,
	codigoCurto CHAR(2) NOT NULL,
	nome VARCHAR(255) NOT NULL,

	CONSTRAINT PK_PAIS PRIMARY KEY (ID)
);

CREATE TABLE Fase
(
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	peso INT NOT NULL,
	aberto INT NOT NULL DEFAULT 0,

	CONSTRAINT PK_PAIS PRIMARY KEY (ID)
);

CREATE TABLE usuario
(
	ID INT NOT NULL AUTO_INCREMENT,
	Login VARCHAR(80) NOT NULL,
	Senha VARCHAR(80) NOT NULL,
	Nome VARCHAR(255) NOT NULL,
	EMail VARCHAR(80) NOT NULL,
	Cidade VARCHAR(255) NOT NULL,
	IDPais INT NOT NULL,
	Foto BLOB,

	CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
	CONSTRAINT FK_IDPAIS FOREIGN KEY (IDPais) REFERENCES pais(ID) on delete cascade
);

CREATE TABLE grupoUsuarios
(
	ID INT NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(255) NOT NULL,
	IDAdministrador INT NOT NULL,

	CONSTRAINT PK_GRUPOUSUARIOS PRIMARY KEY (ID),
	CONSTRAINT FK_IDAdministrador FOREIGN KEY (IDAdministrador) REFERENCES usuario(ID) on delete cascade
);

CREATE TABLE participacaoGrupoUsuarios
(
	IDGrupo INT NOT NULL,
	IDUsuario INT NOT NULL,

	CONSTRAINT PK_PARTICIPACAO PRIMARY KEY (IDGrupo, IDUsuario),
	CONSTRAINT FK_IDGRUPO FOREIGN KEY (IDGrupo) REFERENCES grupoUsuarios(ID) on delete cascade,
	CONSTRAINT FK_IDUSUARIO FOREIGN KEY (IDUsuario) REFERENCES usuario(ID) on delete cascade
);

CREATE TABLE estadio
(
	ID INT NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(40) NOT NULL,
	Cidade VARCHAR(40) NOT NULL,

	CONSTRAINT PK_ESTADIO PRIMARY KEY (ID)
);

CREATE TABLE jogo
(
	Numero INT NOT NULL,
	IDPais1 INT,
	DescricaoPais1 VARCHAR(20),
	IDPais2 INT,
	DescricaoPais2 VARCHAR(20),
	NumeroGrupo INT,
	IDFase INT NOT NULL,
	IDEstadio INT NOT NULL,
	DataHora DATETIME NOT NULL,
	GolsPais1 INT,
	GolsPais2 INT,

	CONSTRAINT PK_JOGO PRIMARY KEY (Numero),
	CONSTRAINT FK_IDFASE FOREIGN KEY (IDFase) REFERENCES fase(ID) on delete cascade,
	CONSTRAINT FK_IDESTADIO FOREIGN KEY (IDESTADIO) REFERENCES estadio(ID) on delete cascade,
	CONSTRAINT FK_IDPAIS1 FOREIGN KEY (IDPais1) REFERENCES pais(ID) on delete cascade,
	CONSTRAINT FK_IDPAIS2 FOREIGN KEY (IDPais2) REFERENCES pais(ID) on delete cascade
);

CREATE TABLE palpite
(
	ID INT NOT NULL AUTO_INCREMENT,
	IDJogo INT NOT NULL,
	IDUsuario INT NOT NULL,
	GolsPais1 INT NOT NULL,
	GolsPais2 INT NOT NULL,
	PontosGanhos INT NOT NULL,
	
	CONSTRAINT PK_PALPITE PRIMARY KEY (ID),
	CONSTRAINT FK_IDJOGO FOREIGN KEY (IDJogo) REFERENCES jogo(Numero) on delete cascade,
	CONSTRAINT FK_PALPITEIDUSUARIO FOREIGN KEY (IDUsuario) REFERENCES usuario(ID) on delete cascade
);
