INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (4, "AFG", "AF", "Afeganistao");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (710, "ZAF", "ZA", "África do Sul");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (8, "ALB", "AL", "Albânia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (276, "DEU", "DE", "Alemanha");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (20, "AND", "AD", "Andorra");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (24, "AGO", "AO", "Angola");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (660, "AIA", "AI", "Anguilla");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (28, "ATG", "AG", "Antigua e Barbuda");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (530, "ANT", "AN", "Antillas Holandesas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (682, "SAU", "SA", "Arábia Saudita");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (12, "DZA", "DZ", "Argélia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (32, "ARG", "AR", "Argentina");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (51, "ARM", "AM", "Armênia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (533, "ABW", "AW", "Aruba");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (36, "AUS", "AU", "Austrália");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (40, "AUT", "AT", "Áustria");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (31, "AZE", "AZ", "Azerbaijão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (44, "BHS", "BS", "Bahamas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (48, "BHR", "BH", "Bahrem");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (50, "BGD", "BD", "Bangladesh");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (52, "BRB", "BB", "Barbados");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (56, "BEL", "BE", "Bélgica");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (84, "BLZ", "BZ", "Belice");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (204, "BEN", "BJ", "Benin");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (60, "BMU", "BM", "Bermudas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (112, "BLR", "BY", "Bielorrusia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (104, "MMR", "MM", "Birmânia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (68, "BOL", "BO", "Bolivia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (70, "BIH", "BA", "Bósnia e Herzegovina");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (72, "BWA", "BW", "Botsuana");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (76, "BRA", "BR", "Brasil");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (96, "BRN", "BN", "Brunei");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (100, "BGR", "BG", "Bulgária");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (854, "BFA", "BF", "Burkina Faso");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (108, "BDI", "BI", "Burundi");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (64, "BTN", "BT", "Butão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (132, "CPV", "CV", "Cabo Verde");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (116, "KHM", "KH", "Camboja");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (120, "CMR", "CM", "Camarões");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (124, "CAN", "CA", "Canadá");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (398, "KAZ", "KZ", "Cazaquistão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (148, "TCD", "TD", "Chade");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (152, "CHL", "CL", "Chile");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (156, "CHN", "CN", "China");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (196, "CYP", "CY", "Chipre");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (170, "COL", "CO", "Colômbia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (174, "COM", "KM", "Comoras");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (178, "COG", "CG", "Congo");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (408, "PRK", "KP", "Coréia do Norte");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (410, "KOR", "KR", "Coréia do Sul");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (384, "CIV", "CI", "Costa do Marfim");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (188, "CRI", "CR", "Costa Rica");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (191, "HRV", "HR", "Croácia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (192, "CUB", "CU", "Cuba");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (208, "DNK", "DK", "Dinamarca");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (262, "DJI", "DJ", "Djibuti");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (212, "DMA", "DM", "Dominica");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (818, "EGY", "EG", "Egito");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (222, "SLV", "SV", "El Salvador");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (784, "ARE", "AE", "Emirados árabes Unidos");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (218, "ECU", "EC", "Equador");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (232, "ERI", "ER", "Eritréia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (703, "SVK", "SK", "Eslováquia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (705, "SVN", "SI", "Eslovênia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (724, "ESP", "ES", "Espanha");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (840, "USA", "US", "Estados Unidos");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (233, "EST", "EE", "Estônia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (231, "ETH", "ET", "Etiópia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (242, "FJI", "FJ", "Fiji");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (608, "PHL", "PH", "Filipinas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (246, "FIN", "FI", "Finlândia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (250, "FRA", "FR", "França");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (266, "GAB", "GA", "Gabão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (270, "GMB", "GM", "Gâmbia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (288, "GHA", "GH", "Gana");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (268, "GEO", "GE", "Geórgia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (292, "GIB", "GI", "Gibraltar");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (308, "GRD", "GD", "Granada");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (300, "GRC", "GR", "Grécia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (304, "GRL", "GL", "Groenlândia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (312, "GLP", "GP", "Guadalupe");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (316, "GUM", "GU", "Guam");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (320, "GTM", "GT", "Guatemala");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (328, "GUY", "GY", "Guiana");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (254, "GUF", "GF", "Guiana Francesa");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (831, "GGY", "GG", "Guernsey");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (324, "GIN", "GN", "Guinea");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (624, "GNB", "GW", "Guinea Bissau");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (226, "GNQ", "GQ", "Guinea Equatorial");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (332, "HTI", "HT", "Haití");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (340, "HND", "HN", "Honduras");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (344, "HKG", "HK", "Hong Kong");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (348, "HUN", "HU", "Hungria");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (248, "ALA", "AX", "Ilhas Aland");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (74, "BVT", "BV", "Ilhas Bouvet");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (136, "CYM", "KY", "Ilhas Caiman");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (166, "CCK", "CC", "Ilhas Cocos");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (184, "COK", "CK", "Ilhas Cook");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (234, "FRO", "FO", "Ilhas Feroe");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (239, "SGS", "GS", "Ilhas Georgias do Sul");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (334, "HMD", "HM", "Ilhas Heard e McDonald");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (238, "FLK", "FK", "Ilhas Malvinas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (833, "IMN", "IM", "Ilhas de Man");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (580, "MNP", "MP", "Ilhas Marianas do Norte");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (584, "MHL", "MH", "Ilhas Marshall");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (162, "CXR", "CX", "Ilhas Navidad");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (612, "PCN", "PN", "Islhas Pitcairn");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (90, "SLB", "SB", "Ilhas Salomon");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (796, "TCA", "TC", "Ilhas Turcas e Caicos");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (92, "VGB", "VG", "Ilhas Virgens Britânicas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (850, "VIR", "VI", "Ilhas Virgens Americanas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (356, "IND", "IN", "índia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (360, "IDN", "ID", "Indonésia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (364, "IRN", "IR", "Irã");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (368, "IRQ", "IQ", "Iraque");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (372, "IRL", "IE", "Irlanda");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (352, "ISL", "IS", "Islândia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (376, "ISR", "IL", "Israel");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (380, "ITA", "IT", "Itália");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (388, "JAM", "JM", "Jamaica");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (392, "JPN", "JP", "Japão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (832, "JEY", "JE", "Jersey");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (400, "JOR", "JO", "Jordânia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (296, "KIR", "KI", "Kiribati");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (414, "KWT", "KW", "Kuwait");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (418, "LAO", "LA", "Laos");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (426, "LSO", "LS", "Lesotho");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (428, "LVA", "LV", "Letônia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (422, "LBN", "LB", "Líbano");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (430, "LBR", "LR", "Libéria");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (434, "LBY", "LY", "Líbia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (438, "LIE", "LI", "Liechtenstein");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (440, "LTU", "LT", "Lituânia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (442, "LUX", "LU", "Luxemburgo");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (446, "MAC", "MO", "Macao");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (450, "MDG", "MG", "Madagascar");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (458, "MYS", "MY", "Malasia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (454, "MWI", "MW", "Malawi");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (462, "MDV", "MV", "Maldivas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (466, "MLI", "ML", "Mali");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (470, "MLT", "MT", "Malta");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (504, "MAR", "MA", "Marrocos");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (474, "MTQ", "MQ", "Martinica");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (480, "MUS", "MU", "Maurício");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (478, "MRT", "MR", "Mauritânia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (175, "MYT", "YT", "Mayotte");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (484, "MEX", "MX", "México");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (583, "FSM", "FM", "Micronésia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (498, "MDA", "MD", "Moldávia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (492, "MCO", "MC", "Mônaco");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (496, "MNG", "MN", "Mongólia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (499, "MNE", "ME", "Montenegro");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (500, "MSR", "MS", "Montserrat");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (508, "MOZ", "MZ", "Moçambique");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (516, "NAM", "NA", "Namíbia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (520, "NRU", "NR", "Nauru");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (524, "NPL", "NP", "Nepal");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (558, "NIC", "NI", "Nicarágua");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (562, "NER", "NE", "Níger");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (566, "NGA", "NG", "Nigéria");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (570, "NIU", "NU", "Niue");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (574, "NFK", "NF", "Norfolk");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (578, "NOR", "NO", "Noruega");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (540, "NCL", "NC", "Nova Caledônia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (554, "NZL", "NZ", "Nova Zelândia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (512, "OMN", "OM", "Oman");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (528, "NLD", "NL", "Holanda");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (585, "PLW", "PW", "Palaos");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (275, "PSE", "PS", "Palestina");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (591, "PAN", "PA", "Panama");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (598, "PNG", "PG", "Papua Nova Guiné");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (586, "PAK", "PK", "Paquistão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (600, "PRY", "PY", "Paraguai");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (604, "PER", "PE", "Peru");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (258, "PYF", "PF", "Polinésia Francesa");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (616, "POL", "PL", "Polônia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (630, "PRI", "PR", "Porto Rico");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (620, "PRT", "PT", "Portugal");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (634, "QAT", "QA", "Qatar");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (404, "KEN", "KE", "Quênia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (417, "KGZ", "KG", "Quirguistão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (826, "GBR", "GB", "Inglaterra");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (140, "CAF", "CF", "República Centroafricana");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (180, "COD", "CD", "Rep. Dem. do Congo");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (214, "DOM", "DO", "República Dominicana");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (203, "CZE", "CZ", "República Tcheca");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (807, "MKD", "MK", "República da Macedônia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (638, "REU", "RE", "Reunião");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (642, "ROU", "RO", "Romênia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (646, "RWA", "RW", "Ruanda");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (643, "RUS", "RU", "Rússia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (732, "ESH", "EH", "República árabe Saharaui Democrática");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (882, "WSM", "WS", "Samoa");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (16, "ASM", "AS", "Samoa Americana");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (652, "BLM", "BL", "São Bartolomeu");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (659, "KNA", "KN", "São Cristóvao e Névis");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (674, "SMR", "SM", "San Marino");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (663, "MAF", "MF", "San Martin");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (666, "SPM", "PM", "São Pedro e Miquelon");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (670, "VCT", "VC", "São Vicente e Granadinas");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (654, "SHN", "SH", "Santa Helena");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (662, "LCA", "LC", "Santa Lucia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (678, "STP", "ST", "São Tomé e Príncipe");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (686, "SEN", "SN", "Senegal");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (688, "SRB", "RS", "Sérvia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (690, "SYC", "SC", "Seychelles");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (694, "SLE", "SL", "Serra Leoa");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (702, "SGP", "SG", "Singapura");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (760, "SYR", "SY", "Síria");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (706, "SOM", "SO", "Somália");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (144, "LKA", "LK", "Sri Lanka");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (748, "SWZ", "SZ", "Suazilândia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (729, "SDN", "SD", "Sudão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (728, "SSD", "SS", "Sudão do Sul");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (752, "SWE", "SE", "Suécia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (756, "CHE", "CH", "Suiça");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (740, "SUR", "SR", "Suriname");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (744, "SJM", "SJ", "Svalbard");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (764, "THA", "TH", "Tailândia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (158, "TWN", "TW", "Taiwan");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (834, "TZA", "TZ", "Tanzânia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (762, "TJK", "TJ", "Tajiquistão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (86, "IOT", "IO", "Território Britânico índico");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (260, "ATF", "TF", "Território Austral Francês");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (626, "TLS", "TL", "Timor Oriental");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (768, "TGO", "TG", "Togo");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (772, "TKL", "TK", "Tokelau");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (776, "TON", "TO", "Tonga");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (780, "TTO", "TT", "Trinidad e Tobago");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (788, "TUN", "TN", "Túnis");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (795, "TKM", "TM", "Turkmenistão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (792, "TUR", "TR", "Turquia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (798, "TUV", "TV", "Tuvalu");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (804, "UKR", "UA", "Ucrânia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (800, "UGA", "UG", "Uganda");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (858, "URY", "UY", "Uruguai");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (860, "UZB", "UZ", "Uzbequistão");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (548, "VUT", "VU", "Vanuatu");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (336, "VAT", "VA", "Vaticano");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (862, "VEN", "VE", "Venezuela");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (704, "VNM", "VN", "Vietnam");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (876, "WLF", "WF", "Wallis e Futuna");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (887, "YEM", "YE", "Yemen");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (894, "ZMB", "ZM", "Zâmbia");
INSERT INTO pais (numero, codigoLongo, codigoCurto, nome) VALUES (716, "ZWE", "ZW", "Zimbabue");
